"""Evidence-based email classification: who sent this, and is there real
evidence of the relationship we think it is?

THE BUG THIS EXISTS TO KILL
gmail_integration.classify_message() builds one haystack out of
subject+sender+snippet+body and returns the first rule whose keyword
appears anywhere in it. Its client_inquiry rule is ("project", "quote",
"bid", "estimate", "proposal"). A GitHub notification titled
"Re: [Buildpro2026/Mark-L] Add candidate matching for construction
project managers" contains "project" — so it came back client_inquiry,
and buildpro_client_intake drafted a business reply to
notifications@github.com. Its automated-sender guard only looked for
"no-reply"/"noreply"/"do-not-reply", which GitHub's address does not
contain.

Adding "github" to an exclusion list would fix exactly GitHub and nothing
else. The actual defect is one of precedence: content keywords were
allowed to establish a business relationship on their own. They cannot.
A keyword says what an email is ABOUT; it says nothing about who sent it
or whether a relationship exists. So the order here is:

    1. WHO sent this        (sender identity — structural, not a blocklist)
    2. WHAT evidence exists (of an actual client/candidate relationship)
    3. Only then, what it is about

A machine sender can never be a client or a candidate no matter what
words its body contains. That single rule is what keeps GitHub out, and
it keeps out every other platform nobody has thought of yet — which a
GitHub-specific exclusion would not.

CONFIDENCE AND ACTION
Every result carries confidence, the evidence supporting it, and the
contradictory evidence found against it. Categories that can trigger
outreach (CLIENT_PROSPECT, CANDIDATE) require affirmative evidence and a
confidence floor; below it, the result is UNKNOWN_NEEDS_REVIEW, which
is a real answer, not a failure. can_act_autonomously() is the single
gate the action paths consult — no caller decides for itself whether a
weak classification is good enough.

Nothing here replaces gmail_integration.classify_message() or
email_classification.classify_email(). Both keep their labels and their
tests. This supplies the precedence gate the first one was missing.
"""
from __future__ import annotations

import re
from typing import Any, Optional

# ── The categories Lee's spec names ──────────────────────────────────────
CLIENT_PROSPECT = "CLIENT_PROSPECT"
CANDIDATE = "CANDIDATE"
PERSONAL = "PERSONAL"
STANDARD_BUSINESS = "STANDARD_BUSINESS"
AUTOMATED_SYSTEM = "AUTOMATED_SYSTEM"
NEWSLETTER_MARKETING = "NEWSLETTER_MARKETING"
TRANSACTIONAL = "TRANSACTIONAL"
RECRUITING_JOB_ALERT = "RECRUITING_JOB_ALERT"
SPAM_JUNK = "SPAM_JUNK"
UNKNOWN_NEEDS_REVIEW = "UNKNOWN_NEEDS_REVIEW"

ALL_CATEGORIES = (
    CLIENT_PROSPECT, CANDIDATE, PERSONAL, STANDARD_BUSINESS, AUTOMATED_SYSTEM,
    NEWSLETTER_MARKETING, TRANSACTIONAL, RECRUITING_JOB_ALERT, SPAM_JUNK,
    UNKNOWN_NEEDS_REVIEW,
)

# Categories that can cause JARVIS to contact a human being. These are the
# ones that need real evidence behind them, because the cost of being
# wrong is an inappropriate email going out under Lee's name.
ACTIONABLE_CATEGORIES = frozenset({CLIENT_PROSPECT, CANDIDATE})

# Below this, an actionable category is downgraded to UNKNOWN_NEEDS_REVIEW.
ACTION_CONFIDENCE_FLOOR = 0.60

# ── Sender identity kinds ────────────────────────────────────────────────
SENDER_MACHINE = "MACHINE"          # generated by a system, no human author
SENDER_BULK = "BULK"                # newsletter/marketing blast
SENDER_HUMAN = "HUMAN"              # a person wrote this to us
SENDER_UNKNOWN = "UNKNOWN"

# Role addresses that are, by convention, not a person. These are lists of
# ROLES, not of companies — they do not need updating when a new platform
# appears, which is the whole point.
#
# Split into two because the roles mean different things. A system role
# sends you notifications about your own account or repository; a
# marketing role sends a campaign to a list. GitHub sets List-Unsubscribe
# and List-Id (one list per repo) on notification mail, so bulk headers
# alone would file every GitHub notification as a newsletter. The role
# is the stronger signal of intent, so a system role outranks the headers.
_SYSTEM_ROLES: tuple[str, ...] = (
    "no-reply", "noreply", "no_reply", "do-not-reply", "donotreply",
    "notifications", "notification", "notify", "alerts", "alert",
    "mailer-daemon", "postmaster", "bounce", "bounces", "auto", "automated",
    "system", "sysadmin", "root", "daemon", "cron", "jenkins", "ci",
    "builds", "build", "support", "help", "helpdesk", "billing",
    "invoices", "receipts", "security", "account", "accounts",
    "verify", "verification", "jobalerts",
)
_MARKETING_ROLES: tuple[str, ...] = (
    "news", "newsletter", "marketing", "promotions", "promo", "offers",
    "deals", "digest", "updates", "update", "hello", "hi", "team",
)
_ROLE_LOCALPARTS: tuple[str, ...] = _SYSTEM_ROLES + _MARKETING_ROLES

# Headers that only automated senders set. Structural proof, not a guess:
# a person's mail client does not add List-Unsubscribe.
_MACHINE_HEADERS: tuple[str, ...] = (
    "list-unsubscribe", "list-id", "auto-submitted", "x-auto-response-suppress",
    "x-mailer-daemon", "feedback-id", "x-campaign-id", "x-mailgun-sid",
    "x-ses-outgoing", "precedence",
)
_BULK_PRECEDENCE = ("bulk", "list", "junk")

# Body text only a generated message contains.
_MACHINE_BODY_MARKERS: tuple[str, ...] = (
    "unsubscribe", "you are receiving this", "you're receiving this",
    "this is an automated", "do not reply to this", "please do not reply",
    "view this email in your browser", "manage your notification",
    "notification settings", "update your preferences", "opt out",
)

_TRANSACTIONAL_MARKERS: tuple[str, ...] = (
    "your receipt", "receipt for", "invoice", "order confirmation",
    "payment received", "payment successful", "your order", "shipped",
    "verification code", "confirm your email", "reset your password",
    "password reset", "two-factor", "security code", "sign-in attempt",
)

_JOB_ALERT_MARKERS: tuple[str, ...] = (
    "job alert", "jobs for you", "new jobs matching", "recommended jobs",
    "jobs you may be interested", "your job alert", "apply now on",
)

_SPAM_MARKERS: tuple[str, ...] = (
    "you have won", "claim your prize", "wire transfer request",
    "cryptocurrency investment", "increase your seo", "buy followers",
    "act now limited time", "risk-free trial today",
)

# ── Affirmative relationship evidence ────────────────────────────────────
# First person, addressed to us, describing a real relationship. A machine
# does not write these about itself.
_CANDIDATE_INTENT = (
    "my resume", "my cv", "attached is my resume", "attached my resume",
    "i am applying", "i'm applying", "i would like to apply",
    "i'd like to apply", "applying for the", "my application",
    "i am interested in the position", "i'm interested in the position",
    "consider me for", "my experience includes", "years of experience in",
    "i am currently working", "i'm currently a", "looking for a new role",
    "seeking a position", "available to start",
)
_CLIENT_INTENT = (
    "we are looking to hire", "we're looking to hire", "we need to hire",
    "looking for a recruiter", "help us find", "help us hire",
    "we have an opening", "we have a position", "requesting a quote",
    "request a quote", "can you send us a proposal", "send me a proposal",
    "interested in your services", "work with your firm",
    "engage your services", "our company is looking", "we are seeking",
    "staffing needs", "hiring needs", "retained search",
)

_RESUME_EXT = (".pdf", ".doc", ".docx", ".rtf", ".odt")
_RESUME_NAME = ("resume", "cv", "curriculum vitae", "curriculumvitae")

_EMAIL_RE = re.compile(r"[\w.+-]+@([\w-]+(?:\.[\w-]+)+)")


def _addr_parts(sender: str) -> tuple[str, str]:
    """(localpart, domain) from a From header, both lowercase. Empty
    strings when the header has no parsable address at all."""
    match = _EMAIL_RE.search(sender or "")
    if not match:
        return "", ""
    address = match.group(0).lower()
    local, _, domain = address.partition("@")
    return local, domain


def _headers_lower(message: dict[str, Any]) -> dict[str, str]:
    raw = message.get("headers") or {}
    if isinstance(raw, list):  # [{"name": ..., "value": ...}] shape
        return {str(h.get("name", "")).lower(): str(h.get("value", ""))
                for h in raw if isinstance(h, dict)}
    return {str(k).lower(): str(v) for k, v in raw.items()}


def _text_of(message: dict[str, Any], body_cap: int = 4000) -> str:
    return " ".join([
        (message.get("subject") or ""),
        (message.get("snippet") or ""),
        (message.get("body") or "")[:body_cap],
    ]).lower()


def is_resume_attachment(filename: str) -> bool:
    name = (filename or "").lower()
    return (any(name.endswith(ext) for ext in _RESUME_EXT)
            and any(marker in name for marker in _RESUME_NAME))


def sender_identity(message: dict[str, Any]) -> dict[str, Any]:
    """Who sent this — decided from structure, not from a list of company
    names. Headers first (a person's client does not set List-Unsubscribe),
    then the role local-part (`notifications@`, `billing@`), then generated
    body markers. Returns the kind plus the exact evidence for it, so a
    misfire can be traced to the signal that caused it."""
    evidence: list[str] = []
    headers = _headers_lower(message)
    sender = (message.get("sender") or "")
    local, domain = _addr_parts(sender)
    text = _text_of(message)

    for header in _MACHINE_HEADERS:
        if header not in headers:
            continue
        if header == "precedence":
            if headers[header].strip().lower() in _BULK_PRECEDENCE:
                evidence.append(f"header Precedence: {headers[header].strip()}")
            continue
        evidence.append(f"header {header}")

    bulk = any(e.startswith("header list-unsubscribe")
               or e.startswith("header list-id")
               or e.startswith("header Precedence")
               or e.startswith("header x-campaign-id")
               or e.startswith("header feedback-id") for e in evidence)

    def _role_match(roles: tuple[str, ...]) -> Optional[str]:
        return next((r for r in roles
                     if local == r or local.startswith(r + ".")
                     or local.startswith(r + "-") or local.startswith(r + "_")
                     or local.endswith("-" + r) or local.endswith("." + r)), None)

    system_role = _role_match(_SYSTEM_ROLES)
    marketing_role = _role_match(_MARKETING_ROLES)
    # A bare hello@/team@ is how plenty of small companies send real human
    # mail, so a marketing role only counts as automation when the bulk
    # headers agree with it.
    if system_role:
        evidence.append(f"system role address '{local}@'")
    elif marketing_role and bulk:
        evidence.append(f"marketing role address '{local}@'")

    body_markers = [m for m in _MACHINE_BODY_MARKERS if m in text]
    if body_markers:
        evidence.append(f"generated-message text: {body_markers[0]!r}")

    # A reply-to pointing somewhere unrelated to the From domain is how
    # notification systems route replies back into their own tracker.
    reply_to = headers.get("reply-to", "")
    if reply_to and domain:
        _, reply_domain = _addr_parts(reply_to)
        if reply_domain and reply_domain != domain:
            evidence.append("reply-to on a different domain than From")

    # A system role means "this is a notification about your account",
    # which is not a marketing list even when it ships list headers.
    if bulk and not system_role and any(
            m in text for m in ("unsubscribe", "update your preferences",
                                "view this email in your browser")):
        kind = SENDER_BULK
    elif evidence:
        kind = SENDER_MACHINE
    elif domain:
        kind = SENDER_HUMAN
        evidence.append("addressed from a mailbox with no automation markers")
    else:
        kind = SENDER_UNKNOWN

    return {"kind": kind, "evidence": evidence, "domain": domain, "localpart": local}


def _relationship_evidence(message: dict[str, Any]) -> dict[str, list[str]]:
    """Affirmative, first-person evidence that a real client or candidate
    relationship exists. Not 'the word project appears somewhere'."""
    text = _text_of(message)
    found: dict[str, list[str]] = {"candidate": [], "client": []}

    for phrase in _CANDIDATE_INTENT:
        if phrase in text:
            found["candidate"].append(f"states {phrase!r}")
    for phrase in _CLIENT_INTENT:
        if phrase in text:
            found["client"].append(f"states {phrase!r}")

    resumes = [a.get("filename") or "" for a in (message.get("attachments") or [])]
    for filename in resumes:
        if is_resume_attachment(filename):
            found["candidate"].append(f"resume attachment {filename!r}")
    return found


def classify(message: dict[str, Any], known_contact: bool = False,
             thread_is_ours: bool = False) -> dict[str, Any]:
    return _classify_inner(message, known_contact, thread_is_ours)


def _classify_inner(message: dict[str, Any], known_contact: bool = False,
                    thread_is_ours: bool = False) -> dict[str, Any]:
    """Full contextual classification.

    known_contact: this sender already exists in HubSpot/candidate records.
    thread_is_ours: this is a reply on a thread we started.

    Both raise confidence but neither can, on its own, turn a machine
    sender into a person — a notification about a contact is still a
    notification.

    Absence of a HubSpot record is never used as evidence FOR anything;
    an unknown sender is unknown, not a prospect."""
    # FORWARDING FIRST (2026-09-08). info@buildprorecruiters.com forwards
    # into Gmail, so the envelope sender can be our own alias rather than
    # the author. Classifying the envelope makes every forwarded candidate
    # look like mail from Lee. resolve_sender() puts the ORIGINAL author in
    # `sender`, and blanks it when the author cannot be recovered — which
    # lands below as UNKNOWN_NEEDS_REVIEW rather than a confident wrong
    # answer about the wrong person.
    from actions import email_forwarding

    forwarding = email_forwarding.analyse(message)
    if forwarding["is_forwarded"] and not forwarding["determined"]:
        return _result(UNKNOWN_NEEDS_REVIEW, 0.0,
                       ["message arrived by forwarding"],
                       [forwarding["reason"]],
                       {"kind": SENDER_UNKNOWN, "domain": "", "evidence": []},
                       {"candidate": [], "client": []}) | {"forwarding": forwarding}
    message = email_forwarding.resolve_sender(message) if forwarding["is_forwarded"] else message

    identity = sender_identity(message)
    text = _text_of(message)
    evidence: list[str] = list(identity["evidence"])
    against: list[str] = []
    if forwarding["is_forwarded"]:
        evidence.append(
            f"forwarded by {forwarding['forwarder_email']}; classified on the "
            f"original sender {forwarding['original_sender_email']}")
    relationship = _relationship_evidence(message)

    # ── Machine and bulk senders resolve on identity alone ───────────────
    if identity["kind"] in (SENDER_MACHINE, SENDER_BULK):
        if relationship["candidate"] or relationship["client"]:
            # Worth recording: this is the exact shape of the GitHub bug,
            # and saying so out loud is how it stays fixed.
            against.append(
                "business-sounding content present, but the sender is not a person — "
                "content cannot establish a relationship a sender contradicts")

        if any(m in text for m in _TRANSACTIONAL_MARKERS):
            category, confidence = TRANSACTIONAL, 0.90
            evidence.append("transactional content (receipt/verification/security)")
        elif any(m in text for m in _JOB_ALERT_MARKERS):
            category, confidence = RECRUITING_JOB_ALERT, 0.85
            evidence.append("job-alert digest content")
        elif identity["kind"] == SENDER_BULK:
            category, confidence = NEWSLETTER_MARKETING, 0.88
            evidence.append("bulk-mail headers with unsubscribe content")
        else:
            category, confidence = AUTOMATED_SYSTEM, 0.90
        return _result(category, confidence, evidence, against, identity, relationship)

    # ── Obvious junk ─────────────────────────────────────────────────────
    if any(m in text for m in _SPAM_MARKERS):
        evidence.append("recognised junk-solicitation phrasing")
        return _result(SPAM_JUNK, 0.75, evidence, against, identity, relationship)

    # ── Human senders: relationship evidence decides ─────────────────────
    if relationship["candidate"]:
        evidence.extend(relationship["candidate"])
        confidence = 0.70 + (0.10 if known_contact else 0.0) + (0.10 if thread_is_ours else 0.0)
        if relationship["client"]:
            against.append("also contains client-intent phrasing")
            confidence -= 0.15
        return _result(CANDIDATE, min(confidence, 0.95), evidence, against, identity, relationship)

    if relationship["client"]:
        evidence.extend(relationship["client"])
        confidence = 0.70 + (0.10 if known_contact else 0.0) + (0.10 if thread_is_ours else 0.0)
        return _result(CLIENT_PROSPECT, min(confidence, 0.95), evidence, against, identity, relationship)

    if identity["kind"] == SENDER_HUMAN:
        # A person wrote to us with no relationship evidence either way.
        # That is ordinary correspondence, not a lead. Calling it a
        # prospect on the strength of an industry word is the bug.
        if any(w in text for w in ("construction", "project", "hiring", "recruiting",
                                   "candidate", "company", "job")):
            against.append(
                "industry vocabulary present but no first-person client or candidate "
                "intent — vocabulary alone is not a relationship")
        category = STANDARD_BUSINESS
        confidence = 0.55
        if _looks_personal(message):
            category, confidence = PERSONAL, 0.60
            evidence.append("personal correspondence with no business content")
        return _result(category, confidence, evidence, against, identity, relationship)

    return _result(UNKNOWN_NEEDS_REVIEW, 0.30, evidence,
                   against + ["sender could not be identified"], identity, relationship)


_PERSONAL_HINTS = ("happy birthday", "see you at dinner", "the kids", "family",
                   "how are you doing", "let's catch up", "hope you're well and")
_BUSINESS_WORDS = ("invoice", "contract", "proposal", "meeting", "client",
                   "candidate", "hiring", "project", "quote", "budget")


def _looks_personal(message: dict[str, Any]) -> bool:
    text = _text_of(message)
    return (any(h in text for h in _PERSONAL_HINTS)
            and not any(b in text for b in _BUSINESS_WORDS))


def _result(category: str, confidence: float, evidence: list[str],
            against: list[str], identity: dict[str, Any],
            relationship: dict[str, list[str]]) -> dict[str, Any]:
    """Apply the confidence floor and assemble the record.

    An actionable category below the floor becomes UNKNOWN_NEEDS_REVIEW
    rather than a weak CLIENT_PROSPECT. A low-confidence guess that can
    send mail is worse than admitting the uncertainty."""
    confidence = round(max(0.0, min(1.0, confidence)), 2)
    downgraded_from = None
    if category in ACTIONABLE_CATEGORIES and confidence < ACTION_CONFIDENCE_FLOOR:
        downgraded_from = category
        category = UNKNOWN_NEEDS_REVIEW
        against = against + [
            f"confidence {confidence} is below the {ACTION_CONFIDENCE_FLOOR} floor "
            f"required to act on {downgraded_from}"]
    return {
        "category": category,
        "confidence": confidence,
        "evidence": evidence,
        "contradictory_evidence": against,
        "sender_kind": identity["kind"],
        "sender_domain": identity["domain"],
        "downgraded_from": downgraded_from,
        "relationship_evidence": relationship,
        "forwarding": None,   # replaced by classify() when relevant
    }


def can_act_autonomously(result: dict[str, Any]) -> tuple[bool, str]:
    """The single gate every automatic action consults before contacting a
    human. Returns (allowed, reason) — the reason is recorded either way,
    so a blocked action is auditable rather than a silent no-op."""
    category = result.get("category")
    if category not in ACTIONABLE_CATEGORIES:
        return False, f"{category} is not a category JARVIS may act on autonomously"
    if result.get("sender_kind") in (SENDER_MACHINE, SENDER_BULK):
        return False, "the sender is an automated system, not a person"
    confidence = float(result.get("confidence") or 0.0)
    if confidence < ACTION_CONFIDENCE_FLOOR:
        return False, f"confidence {confidence} is below the {ACTION_CONFIDENCE_FLOOR} floor"
    if not (result.get("relationship_evidence") or {}).get(
            "candidate" if category == CANDIDATE else "client"):
        return False, "no affirmative evidence of the relationship this action assumes"
    return True, f"{category} at confidence {confidence} with supporting evidence"
